config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: "dashboard#index", as: "authenticated_root"
  end
  
  root to: "welcome#index"

  namespace :api do
    resources :properties do
      get :search, on: :collection
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
  validates :year_built, presence: true
  validates :bathroom, presence: true
  validates :bedroom, presence: true
  validates :lot_size, presence: true
  validates :sqft, presence: true
  validates :house_type, presence: true
  validates :zpid, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  has_many :properties

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/api/properties_controller.rb
module Api
  class PropertiesController < ApplicationController
    def index
      properties = current_user.properties
      render json: properties
    end

    def search
      zwid = Zillow.new
      properties = zwid.find_properties(params[:query])

      render json: properties
    end

    def create
      @property = Property.new(property_params)
      @property.user = current_user
      if @property.save
        render json: @property
      else
        render json: @property.errors, status: :unprocessable_entity
      end
    end

    def property_params
      params.require(:property).permit(
        :user_id,
        :address,
        :city,
        :state,
        :zipcode,
        :year_built,
        :bathroom,
        :bedroom,
        :lot_size,
        :sqft,
        :house_type,
        :zpid,
        :zestimate,
        :rent,
        :portfolio
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def to_boolean(var)
    var == "true" ? true : false
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<%= react_component 'DashboardApplication' %>

app/views/layouts/_flash.html.erb
<div id="flash-messages">
  <% flash.each do |type, msg| %>
    <div class="flash <%= type %>">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="homepage-footer">
  <div class="container">
    <p class="text-muted">
      My Footer goes here
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">RE Portfolio</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="page-wrap">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RE Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="page-wrap">
      <div class="homescreen">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/flash' %>
      <div id="login-box">
        <div class="labels">
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
          <%= f.label :login %>
          <%= f.text_field :login, autofocus: true, id:"username" %></br>

          <%= f.label :password %>
          <%= f.password_field :password, id:"password" %></br>

          <%= f.submit 'Sign In', class:"button" %></br>

          <%= link_to "Forgot your password?", new_password_path(:user) %></br>

          <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>